<?php

namespace Training\TrainingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PopulateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Training\TrainingBundle\Controller\PopulateController();
        return $instance;
    }
}
