<?php

namespace Training\TrainingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DogController__JMSInjector
{
    public static function inject($container) {
        require_once '/Users/adunphy/levels/app/cache/prod/jms_diextra/proxies/Training-TrainingBundle-Controller-DogController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Training\\TrainingBundle\\Controller\\DogController' => array('newAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_0049c74efb2ab780a394b31f34e4d5d52c81a7ff\__CG__\Training\TrainingBundle\Controller\DogController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
