<?php

namespace Training\TrainingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DefaultController__JMSInjector
{
    public static function inject($container) {
        require_once '/Users/adunphy/levels/app/cache/dev/jms_diextra/proxies/Training-TrainingBundle-Controller-DefaultController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Training\\TrainingBundle\\Controller\\DefaultController' => array('aboutAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_3bb4edeb90b986a200bd4e2544c351020812bd44\__CG__\Training\TrainingBundle\Controller\DefaultController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
