<?php

namespace Training\TrainingBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TrainingSessionController__JMSInjector
{
    public static function inject($container) {
        require_once '/Users/adunphy/levels/app/cache/dev/jms_diextra/proxies/Training-TrainingBundle-Controller-TrainingSessionController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Training\\TrainingBundle\\Controller\\TrainingSessionController' => array('newAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_2cbfaa0d41728f99733a5b63af8d67ab10629bb3\__CG__\Training\TrainingBundle\Controller\TrainingSessionController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
